-- Run this against the PostgreSQL database created in Render.
-- This script creates tables and indexes in the selected database; it does not create a database.

CREATE TABLE IF NOT EXISTS users (
  u_id VARCHAR(128) PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(254) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(16) NOT NULL DEFAULT 'Signer' CHECK (role IN ('Admin', 'Signer', 'Listener')),
  total_signs INTEGER NOT NULL DEFAULT 0 CHECK (total_signs >= 0),
  total_sessions INTEGER NOT NULL DEFAULT 0 CHECK (total_sessions >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS gestures_catalog (
  gesture_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gesture_label VARCHAR(32) NOT NULL UNIQUE,
  sample_count INTEGER NOT NULL DEFAULT 0 CHECK (sample_count >= 0)
);

CREATE TABLE IF NOT EXISTS sessions (
  sessions_id VARCHAR(128) PRIMARY KEY,
  u_id VARCHAR(128) NOT NULL REFERENCES users (u_id) ON DELETE CASCADE,
  started_at TIMESTAMPTZ NOT NULL,
  ended_at TIMESTAMPTZ,
  signs_detected INTEGER NOT NULL DEFAULT 0 CHECK (signs_detected >= 0),
  unique_signs INTEGER NOT NULL DEFAULT 0 CHECK (unique_signs >= 0)
);
CREATE INDEX IF NOT EXISTS idx_sessions_user_started ON sessions (u_id, started_at DESC);

CREATE TABLE IF NOT EXISTS history (
  history_id VARCHAR(128) PRIMARY KEY,
  u_id VARCHAR(128) NOT NULL REFERENCES users (u_id) ON DELETE CASCADE,
  sessions_id VARCHAR(128) NOT NULL REFERENCES sessions (sessions_id) ON DELETE CASCADE,
  sign VARCHAR(32) NOT NULL,
  confidence NUMERIC(5,2) NOT NULL CHECK (confidence >= 0 AND confidence <= 100),
  detected_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_history_user ON history (u_id);
CREATE INDEX IF NOT EXISTS idx_history_session ON history (sessions_id);
CREATE INDEX IF NOT EXISTS idx_history_detected_at ON history (detected_at DESC);
CREATE INDEX IF NOT EXISTS idx_history_debounce ON history (u_id, sessions_id, sign, detected_at DESC);

CREATE TABLE IF NOT EXISTS reports (
  report_id VARCHAR(128) PRIMARY KEY,
  u_id VARCHAR(128) NOT NULL REFERENCES users (u_id) ON DELETE CASCADE,
  sign VARCHAR(32) NOT NULL,
  count INTEGER NOT NULL DEFAULT 0 CHECK (count >= 0),
  total_confidence NUMERIC(12,2) NOT NULL DEFAULT 0,
  avg_confidence NUMERIC(5,2) NOT NULL DEFAULT 0 CHECK (avg_confidence >= 0 AND avg_confidence <= 100),
  first_seen TIMESTAMPTZ NOT NULL,
  last_seen TIMESTAMPTZ NOT NULL,
  UNIQUE (u_id, sign)
);

CREATE OR REPLACE FUNCTION update_detection_summaries()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  INSERT INTO reports (report_id, u_id, sign, count, total_confidence, avg_confidence, first_seen, last_seen)
  VALUES (md5(NEW.u_id || ':' || NEW.sign), NEW.u_id, NEW.sign, 1, NEW.confidence, NEW.confidence, NEW.detected_at, NEW.detected_at)
  ON CONFLICT (u_id, sign) DO UPDATE SET
    count = reports.count + 1,
    total_confidence = reports.total_confidence + EXCLUDED.total_confidence,
    avg_confidence = ROUND((reports.total_confidence + EXCLUDED.total_confidence) / (reports.count + 1), 2),
    last_seen = GREATEST(reports.last_seen, EXCLUDED.last_seen);

  UPDATE users SET total_signs = total_signs + 1 WHERE u_id = NEW.u_id;
  UPDATE sessions
  SET signs_detected = signs_detected + 1,
      unique_signs = (
        SELECT COUNT(DISTINCT sign)::INTEGER FROM history WHERE sessions_id = NEW.sessions_id
      )
  WHERE sessions_id = NEW.sessions_id;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS history_after_insert ON history;
CREATE TRIGGER history_after_insert
AFTER INSERT ON history
FOR EACH ROW EXECUTE FUNCTION update_detection_summaries();

CREATE OR REPLACE VIEW session_summary AS
SELECT s.sessions_id, s.u_id, u.name, s.started_at, s.ended_at,
       s.signs_detected, s.unique_signs
FROM sessions s
JOIN users u ON u.u_id = s.u_id;
